### ISSUE TITLE
изменить код генерации

### ISSUE THREAD

**Issue by sunforgb** [sunforgb/hadoop_labs#2]
Необходимо изменить код генерации списка товаров в Faker.py.
В первую очередь изменить название исходника.
Во вторую очередь - поменять на list/dict comprehensions. 
Третье - необходимо инициализировать random сидом, чтобы числа генерировались на основании всегда разного числа.

**Comment by Hermainy** [comment]
1) Название исходного файла поменял на DateGenerator.py
2) Изменил для списка positions использование обычных итераций на List Comprehension 
3) Инициализировал seed перед генерацией числа

**Comment by sunforgb** [comment]
пункт 3 выполнен неверно
пункт 2 - немного неверно и можно лучше
